name: Spring Back CI/CD

on:
  pull_request:
    branches: [main]
  push:
    branches: [dev]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: "./back"

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: mvn clean test

      - name: Upload coverage reports
        #if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: ./back/target/surefire-reports

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_BACK }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
        with:
          # projectBaseDir: ./back
          args: >
            -Dsonar.projectKey=ask0ldd_p10cicdback
            -Dsonar.organization=ask0ldd
            -Dsonar.sources=./back/src/main/java
            -Dsonar.java.binaries=./back/target/classes/com/openclassrooms/bobapp
            -Dsonar.coverage.jacoco.xmlReportPaths=./back/target/site/jacoco/jacoco.xml
            -Dsonar.exclusions=front/.angular/**,front/node_modules/**,front/coverage/**,front/src/environments/**,.git,.github,back/target/**,back/src/test/**,**/*.spec.ts,**/*.conf.js

      - name: Docker Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_TOKEN

      - name: Build and Push Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          docker build -t $DOCKER_USERNAME/bobappback:latest .
          docker push $DOCKER_USERNAME/bobappback:latest
